#include  "Array.hpp"

int main()
{
    try
    {
        
    }
    catch(const std::exception& e)
    {
        std::cout << e.what() << std::endl;
    }
    
}